# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""empty message

Revision ID: ef6cf4c31b2b
Revises: 5cc1b19bd39c
Create Date: 2025-03-07 02:16:22.740875

"""

# revision identifiers, used by Alembic.
revision = 'ef6cf4c31b2b'
down_revision = '5cc1b19bd39c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_access_logs', sa.Column('dashboard_name', sa.String(length=500), nullable=True))
    op.add_column('dashboard_access_logs', sa.Column('project_name', sa.String(length=500), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard_access_logs', 'project_name')
    op.drop_column('dashboard_access_logs', 'dashboard_name')
    # ### end Alembic commands ###
